### ISSUE TITLE
ConjureBodySerDe does not support alias of optional responses

### ISSUE THREAD

**Issue by pkoenig10** [palantir/dialogue#573]
## What happened?
When an endpoint returns an alias of an empty optional, the [conjure spec](https://github.com/palantir/conjure/blob/master/docs/spec/wire.md#31-status-codes) requires a 204 response with an empty body. When deserializing this response, Dialogue throws the following exception:
https://github.com/palantir/dialogue/blob/bb92eac336ba9e2e0938ed1d6b4248f61114fee9/dialogue-serde/src/main/java/com/palantir/conjure/java/dialogue/serde/ConjureBodySerDe.java#L218-L219

This is handled in conjure-java-runtime, by using reflection to detect alias of optional types:
https://github.com/palantir/conjure-java-runtime/blob/7761d1063e96fd53e46bf2f76596e14f12856488/conjure-java-jaxrs-client/src/main/java/com/palantir/conjure/java/client/jaxrs/feignimpl/EmptyContainerDecoder.java#L106-L123

**Comment by iamdanfox** [comment]
Note I think we need to put in some handling for map, list or set which should also accept 204s as their empty variant. [spec](https://github.com/palantir/conjure/blob/master/docs/spec/wire.md#31-status-codes)

We should be able to do this without any reflection for known conjure types, but people might be relying on their own hand-rolled types (which currently work in the feign jax-rs world due to reflection).

**Comment by pkoenig10** [comment]
Conjure already generates a default constructor for alias of optional types. Can we first add support for Conjure types using this constructor and then fix external types later?
https://github.com/palantir/conjure-java/blob/583b255bdede898648d339470e1d8cf60fe4a2a5/conjure-java-core/src/main/java/com/palantir/conjure/java/types/AliasGenerator.java#L116-L119
