### ISSUE TITLE
Feature request: First-class way to connect to subsets of hosts for a service

### ISSUE THREAD

**Issue by henryptung** [palantir/dialogue#999]
For a sharded service like Horizon, some hosts are mirrors of each other and should be treated with normal Conjure/Dialogue redundancy semantics, and other hosts represent different shards and should not be part of the redundancy pool (for this specific shard). There would be one such client per shard (for read/query purposes).

As far as I'm aware, there's no way to go from a Refreshable<List<Channel>> per-host channel list to a redundant client (i.e. to indirectly invoke NodeSelectionStrategyChannel

API proposal:

```
interface PerHostClientFactory {
    Channel getChannelMatchingFilter(Predicate<String> endpointUriFilter); // <- Maybe Refreshable<Predicate<String>>?

    <T> T getClientMatchingFilter(Predicate<String> endpointUriFilter);
}
```

**Comment by carterkozak** [comment]
Would it make sense to pass the DialogueClients factory a services block where each shard has a unique name? e.g. `horizon-shard-0` and `horizon-shard-1` where each of these may have N mirrors as standard uri lists?

Longer term it would be interesting to support a first-class sharding mechanism in dialogue, but there are a lot of unknowns and I'm not sure if it's common enough to warrant adding to the core libray.

**Comment by henryptung** [comment]
@carterkozak Problem with that is that the shards aren't pre-set. If someone has 45 shards, they're not going to create 45 different Horizon services and maintain configuration for all of them independently (so there's no way to put "uris for shard 32" in a Skylab config list - the shard assignment is in DB).

We are doing an approach like this (a Refreshable<ServiceConfigBlock> made via Java code) in a very limited fashion for Horizon node<->node communication, but it's pretty hacky to produce a "magic" ServiceConfigBlock and a new ReloadingFactory each time a new HorizonCluster is seen. Would prefer not to have to do the same in Dispatch.

**Comment by carterkozak** [comment]
Right, I’m not suggesting that we consider each shard a unique service, rather that we do a transformation in code (serviceConfigRefreshable.map) into a structure which separates nodes by shard with a given shard identifier as the “service name”. I think it’s equivalent to the structure you have proposed, but the predicate becomes a classifier function that’s run on config refresh, and instead of passing a predicate to get a channel or client, we pass its identifier (shard-id-as-service-name).
I might be missing something, happy to chat tomorrow if you can put some time on my calendar!

**Comment by henryptung** [comment]
Workaround: Preprocess the ServicesConfigBlock and create a custom client factory for individual use case
